version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ".:/app"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"